defmodule PlugboardWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :plugboard

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Session salts are configured via environment variables in production.
  # See config/runtime.exs for production configuration.
  defp session_options do
    session_config = Application.get_env(:plugboard, :session, [])

    signing_salt =
      Keyword.get(session_config, :signing_salt) ||
        raise_missing_session_salt!(:signing_salt)

    encryption_salt = Keyword.get(session_config, :encryption_salt)

    base_opts = [
      store: :cookie,
      key: "_plugboard_key",
      signing_salt: signing_salt,
      same_site: "Lax",
      secure: Application.get_env(:plugboard, :env) == :prod
    ]

    if encryption_salt do
      Keyword.put(base_opts, :encryption_salt, encryption_salt)
    else
      base_opts
    end
  end

  defp raise_missing_session_salt!(salt_type) do
    env_var =
      case salt_type do
        :signing_salt -> "SESSION_SIGNING_SALT"
        :encryption_salt -> "SESSION_ENCRYPTION_SALT"
      end

    raise """
    Session #{salt_type} is not configured!

    Set the #{env_var} environment variable.
    You can generate a salt with: mix phx.gen.secret 32
    """
  end

  # LiveView socket must use the same session options as Plug.Session
  # We read from compile-time config to match what session_options() will use at runtime
  # For production, session config must also be set in config/prod.exs (compile-time)
  # in addition to config/runtime.exs (runtime)
  @session_config Application.compile_env(:plugboard, :session, [])
  @session_signing_salt Keyword.get(
                          @session_config,
                          :signing_salt,
                          "dev_signing_salt_not_for_production"
                        )
  @session_encryption_salt Keyword.get(@session_config, :encryption_salt)
  @env Application.compile_env(:plugboard, :env, :dev)

  @session_options (
                     base_opts = [
                       store: :cookie,
                       key: "_plugboard_key",
                       signing_salt: @session_signing_salt,
                       same_site: "Lax",
                       secure: @env == :prod
                     ]

                     if @session_encryption_salt do
                       Keyword.put(base_opts, :encryption_salt, @session_encryption_salt)
                     else
                       base_opts
                     end
                   )

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  socket("/telephone", PlugboardWeb.TelephoneSocket,
    websocket: true,
    longpoll: false
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :plugboard,
    gzip: not code_reloading?,
    only: PlugboardWeb.static_paths()
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket("/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket)
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :plugboard)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  # Request body parsing with runtime-configurable max body size
  # See PlugboardWeb.Plugs.Parsers for details
  # Configured via MAX_REQUEST_BODY_SIZE env var (default: 10MB)
  plug(PlugboardWeb.Plugs.Parsers)

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(:session)

  # Use runtime session options for Plug.Session to support production runtime config
  # The LiveView socket uses @session_options (compile-time) which must match
  defp session(conn, _opts) do
    Plug.Session.call(conn, Plug.Session.init(session_options()))
  end

  # WebSocket proxy - intercepts WebSocket upgrade requests before the router
  # and proxies them through Telephone sidecars to backend services
  plug(PlugboardWeb.Plugs.WebSocketProxyPlug)

  plug(PlugboardWeb.Router)
end
