import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :plugboard, PlugboardWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Initialize plugs at runtime for configuration via environment variables
config :phoenix, :plug_init_mode, :runtime

# Compile-time configuration from environment variables
# Must be set during Docker build
config :plugboard,
       :max_request_body_length,
       System.get_env("MAX_REQUEST_BODY_SIZE") |> String.to_integer()

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
